tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface-tint": "#c8c6c5",
              "on-primary-fixed": "#1c1b1b",
              "on-surface": "#e4e2e1",
              "primary-fixed": "#e5e2e1",
              outline: "#8e9192",
              "on-background": "#e4e2e1",
              background: "#131313",
              "on-secondary-fixed": "#1a1c1c",
              "secondary-fixed": "#e2e2e2",
              "outline-variant": "#444748",
              "on-tertiary-fixed-variant": "#872000",
              "on-error": "#690005",
              primary: "#c8c6c5",
              "surface-variant": "#353535",
              tertiary: "#ffb5a0",
              "surface-bright": "#393939",
              "tertiary-fixed-dim": "#ffb5a0",
              "surface-container-high": "#2a2a2a",
              "inverse-primary": "#5f5e5e",
              secondary: "#c6c6c6",
              surface: "#131313",
              "on-secondary-container": "#b5b5b5",
              "surface-container-highest": "#353535",
              "surface-container-low": "#1b1c1c",
              "on-primary-fixed-variant": "#474646",
              "tertiary-fixed": "#ffdbd1",
              "surface-dim": "#131313",
              error: "#ffb4ab",
              "surface-container-lowest": "#0e0e0e",
              "on-secondary-fixed-variant": "#454747",
              "primary-container": "#121212",
              "on-primary": "#313030",
              "on-secondary": "#2f3131",
              "inverse-on-surface": "#303030",
              "on-tertiary": "#601400",
              "surface-container": "#1f2020",
              "on-surface-variant": "#c4c7c7",
              "secondary-fixed-dim": "#c6c6c6",
              "tertiary-container": "#2a0500",
              "error-container": "#93000a",
              "on-primary-container": "#7e7d7d",
              "primary-fixed-dim": "#c8c6c5",
              "secondary-container": "#454747",
              "on-error-container": "#ffdad6",
              "on-tertiary-container": "#e83e00",
              "on-tertiary-fixed": "#3b0900",
              "inverse-surface": "#e4e2e1",
              "brand-orange": "#FF4500",
              "brand-silver": "#E5E5E5",
            },
            borderRadius: {
              DEFAULT: "0.125rem",
              lg: "0.25rem",
              xl: "0.5rem",
              full: "0.75rem",
            },
            spacing: {
              "margin-mobile": "20px",
              "container-max": "1280px",
              "stack-md": "12px",
              base: "8px",
              "stack-lg": "32px",
              gutter: "24px",
              "stack-sm": "4px",
              "margin-desktop": "64px",
            },
            fontFamily: {
              "display-lg": ["Montserrat", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "headline-md": ["Montserrat", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "label-caps": ["JetBrains Mono", "monospace"],
              "headline-lg": ["Montserrat", "sans-serif"],
              "headline-lg-mobile": ["Montserrat", "sans-serif"],
            },
            fontSize: {
              "display-lg": [
                "64px",
                {
                  lineHeight: "1.1",
                  letterSpacing: "-0.02em",
                  fontWeight: "800",
                },
              ],
              "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
              "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
              "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
              "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
              "label-caps": [
                "14px",
                {
                  lineHeight: "1.0",
                  letterSpacing: "0.1em",
                  fontWeight: "500",
                },
              ],
              "headline-lg": [
                "40px",
                {
                  lineHeight: "1.2",
                  letterSpacing: "-0.01em",
                  fontWeight: "700",
                },
              ],
              "headline-lg-mobile": [
                "32px",
                { lineHeight: "1.2", fontWeight: "700" },
              ],
            },
          },
        },
      };
    